update pipeline ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,7 +49,7 @@ jobs:
       - name: Criar artefato report.zip
         run: |
           echo "::notice::Creating artifact with report files"
-          zip report.zip status-check.sh README.md || echo "::error::Failed to create artifact
+          zip report.zip status-check.sh README.md || echo "::error::Failed to create artifact"
 
       - name: Upload do artefato
         uses: actions/upload-artifact@v4
